AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  AllowedMethods:
    - insert_includes
    - formed_key

Metrics/PerceivedComplexity:
  AllowedMethods:
    - insert_includes
    - formed_key

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
